### PR TITLE
Add IK modifications back to project (Godot 4.0)

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
Added IK modifications to all IK test scenes. Slightly modified code to get it working withe latest changes in GDScript.

### CODE REVIEW

**Comment by fire** [comment]
Cheers

**Comment by fire** [comment]
Any comments on defaulting the skeletons modifications to be on in the editor?

**Comment by TwistedTwigleg** [comment]
> Any comments on defaulting the skeletons modifications to be on in the editor?

Good question!
I think it’s probably best to have it default as off, as otherwise the console would spam with errors and it wouldn’t work until fully setup anyway for the overwhelming majority of the IK modifiers. The modifiers themselves default to being active though, so it’s just a single checkbox (`enabled`) in the stack holder to turn it on, even when setting up.

That said though, it’s trivial to change if users report that they’d rather have it default to on, but right now from my perspective, I think it’s best to have it default to off.

**Comment by fire** [comment]
I mean in the engine core - default to off. In this specific demo, default them to on as they're setup.

**Comment by TwistedTwigleg** [comment]
The stack or the modifications themselves? The modifications should be enabled by default ([source](https://github.com/godotengine/godot/blob/master/scene/resources/skeleton_modification_3d.h#L50)). The stack however, should probably be disabled by default, for the reasons I mentioned previously.

**Comment by fire** [comment]
Thanks for explaining.

**Comment by TwistedTwigleg** [comment]
No problem, and thanks for the question! I wasn't totally sure right off and had to look at the code, so it was good to get more familiar with the code again.

I haven't had the time to check with a nightly/daily build just yet, but I am going to merge it in for now and can always make another commit and PR if necessary after if more fixes are needed.

**Pull request merged**
